### ISSUE TITLE
Error when open vue-cli-gui

### ISSUE THREAD

**Issue by ChangJoo-Park** [egoist/vue-cli-gui#1]
![image](https://user-images.githubusercontent.com/1451365/40962745-5e9baaae-68e1-11e8-9881-eb48130e9c3e.png)

I just run vue-cli-gui on my High Sierra.  
Is this message useful?

**Comment by egoist** [comment]
Seems `vue` command is not found, do you have `@vue/cli` globally installed?

**Comment by ChangJoo-Park** [comment]
Sure :) But I used old version of`@vue/cli`. 
I reinstall `@vue/cli` 3.0.0-beta.15. 
Now, I saw empty one.

![image](https://user-images.githubusercontent.com/1451365/40964338-d55eda7c-68e5-11e8-89a7-04a3aa6c27e7.png)

**Comment by egoist** [comment]
You can toggle developer tool to see what's going on there, maybe you're behind a proxy

**Comment by sinchang** [comment]
same problem with `@vue/cli 2.9.3`

**Comment by egoist** [comment]
@sinchang only works with `@vue/cli` 😅

**Comment by sinchang** [comment]
my fault.  👍

**Comment by savokiss** [comment]
I use `vue ui` command in the terminal and open the gui again then it works fine.

Using @vue/cli 3.0.0-beta.15

**Comment by ChangJoo-Park** [comment]
It breaks on 0.0.1 too 😭 
![image](https://user-images.githubusercontent.com/1451365/41014018-6a965b9a-6983-11e8-80d1-29a749792655.png)

**Comment by egoist** [comment]
@ChangJoo-Park is `vue ui` command working for you? this app basically runs `vue ui` command in a child process and loads http://localhost:8000 in the electron window 😅

**Comment by ChangJoo-Park** [comment]
maybe It because using `nvm`.
installed vue cli path is `/Users/changjoopark/.nvm/versions/node/v9.11.1/bin/vue`.

**Comment by ChangJoo-Park** [comment]
When I start this app using npm script `npm run main` it works well. but after build, it fails 😭

**Comment by egoist** [comment]
Should work now: https://github.com/egoist/vue-cli-gui/releases/tag/v0.0.2

**Comment by ChangJoo-Park** [comment]
It works well! 👍
