### ISSUE TITLE
Any Windows Plan?

### ISSUE THREAD

**Issue by mashirozx** [egoist/vue-cli-gui#2]
Looking forward to a Windows version...![image](https://user-images.githubusercontent.com/16148054/40966898-494aac56-68e4-11e8-9d27-52415d21d77a.png)

**Comment by egoist** [comment]
Maybe later, I don't have a window machine so I have to setup https://www.appveyor.com/ for automatic deploy.

**Comment by mashirozx** [comment]
Great, thank you!

**Comment by egoist** [comment]
btw if you want to use it now, just clone it and run `yarn dist`

**Comment by mashirozx** [comment]
@egoist Well, I'll try latter.  :smile:

**Comment by YannMCX** [comment]
Hello,
I have successfully executed the "ui view" command from node under Windows, here is the line to modify ^^'' 

```javascript
const cmd = spawn('cmd.exe', ['/c', 'vue', 'ui']);
```
I hope it will be useful: D

PS: Sorry, I'm quite new to GitHub, moreover, a PR on my part would provide much more work than necessary (my knowledge of Javascript is quite limited).
